# Generated by Django 2.2.3 on 2019-07-30 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20190730_0031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ideia',
            old_name='pressoa',
            new_name='pessoa',
        ),
    ]
